all: scheduler

timer: timer.cpp
	g++ timer.cpp -o timer -lrt

scheduler: scheduler.cpp
	g++ scheduler.cpp -o scheduler -lrt

fancyscheduler: fancyscheduler.cpp
	g++ fancyscheduler.cpp -o fancyscheduler -lrt

