include(CewDir/bin/cew.gdb)
# Cew for asm Testing Script
# Peter Walsh Feb 2001



#------------ gdb/cew Initialization ---------------
   set remotebaud 9600
   target buffalo /dev/ttyS0
   #target sim
   load wave.elf
   set language c
   cew_Variables


#-------------- Local Constants -------------------
#none
#-------------- Local Functions -------------------
#none

#---------------- Test Cases -----------------------


   run
   cew_Summary
   quit
